### ISSUE TITLE
Move environment modules to glimmer-application repo.

### ISSUE THREAD

**Issue by rwjblue** [glimmerjs/glimmer-component#2]
The following files seem like they belong in the https://github.com/glimmerjs/glimmer-application repo instead:

- [ ] https://github.com/glimmerjs/glimmer-component/blob/master/src/environment.ts
- [ ] https://github.com/glimmerjs/glimmer-component/blob/master/src/iterable.ts

**Comment by dgeb** [comment]
Agreed. These were created here for expediency. 

Once we move these over we'll need to add equivalents here as test helpers.

**Comment by dgeb** [comment]
🚧 I'm working on this now 🚧
