### ISSUE TITLE
Feedback on glimmerjs.com

### ISSUE THREAD

**Issue by whitneyland** [glimmerjs/glimmer-component#29]
Congratulations on launching an ambitious project.  I'm listing here a few criticisms on your landing page that I hope you will take as constructive.  As much effort as goes into projects like this, they deserve at least enough attention to get a fair sake from devs.

Suggestions for possible changes:

1. UI components for what?  Visitors should get this clear immediately
2. "Attention to detail of ember" - is that a quality comparison, or is it only for ember framework?
3. UI projects should have at least one or two screenshots
4. Should mention at least one actual feature or component
5. GitHub link doesn't go to a repo. Instead it's a list of repos that you have to click around in to find the main project.
6. API docs link goes to a page that is blank except for another link to the actual API docs.  If docs are not ready better to just link to "#", avoid frustration 

Best of luck going forward,
Lee

Btw, on a positive note you made front page of HN. :)
https://news.ycombinator.com/item?id=13979014

**Comment by rwjblue** [comment]
@whitneyland - Thank you for taking the time to write up such a detailed listing of tactical things to fix/address! I'll try to circle around with the others and come up with a game plan...

**Comment by dgeb** [comment]
Yes, much appreciated! Unfortunately the site's content was put together under a very tight schedule, but we'll try to improve it very soon.

**Comment by acorncom** [comment]
Opened a new issue on the glimmer-website repo now that it's public: https://github.com/tomdale/glimmer-website/issues/27

**Comment by locks** [comment]
Closing this so as not to confuse people, thank you!
