### ISSUE TITLE
Type checking errors with this.args

### ISSUE THREAD

**Issue by mmun** [glimmerjs/glimmer-component#38]
Referencing `this.args.todo` and `this.args.onEdit` in my component gives these type errors:

```
/src/ui/components/todo-item/component.ts(12,31): Property 'todo' does not exist on type 'object'.
/src/ui/components/todo-item/component.ts(17,15): Property 'onEdit' does not exist on type 'object'.
/src/ui/components/todo-item/component.ts(17,32): Property 'todo' does not exist on type 'object'.
```

Is there a more permissive type we can use for "bag of arbitrary properties"?

**Comment by robbiepitts** [comment]
Perhaps `Dict<any>`?

**Comment by mmun** [comment]
I'm relatively new to TypeScript, but I think the idea is to _redefine_ the type of `args` when you subclass the `Component`. For example, https://github.com/glimmerjs/todomvc-demo/commit/87e93bc133211d18fd00ed5280b8b5d6a9fd00b1#diff-09bb10ea80bb98211c9cdb650d57b44bR9.

**Comment by rwjblue** [comment]
Yes, that seems good.  We should also try to add some special sauce to verify template invocations pass the right args if you have defined a custom interface for `args` like this...

**Comment by mmun** [comment]
I'd love to spike this out! :)
