### ISSUE TITLE
No documented block params

### ISSUE THREAD

**Issue by Samsinite** [glimmerjs/glimmer-component#39]
First off, love the work put towards glimmer.

Just playing around with glimmer-components and I noticed that yields work, but they seem undocumented. Are block params currently supported? If so, what is their syntax? If not, is this a planned feature of the glimmer view layer? Is there any good workarounds to get a block param like feature if it isn't supported?

**Comment by Samsinite** [comment]
Looks like I was able to yield params and use them similar to ember:

```hbs
<my-component as |yielded|>{{yielded}} was yielded</my-component>
```

`my-component.hbs`
```hbs
<div>{{yield "Test"}}</div>
```

**Comment by locks** [comment]
This API is not public at the moment.

**Comment by Samsinite** [comment]
Is it something that is going to be public? If so, is the interface defined? If it is, is there interest in beginning to write documentation around that interface?

**Comment by locks** [comment]
@Samsinite I have been told that I was overcautious and this is to be considered public. Want to write the relevant guide for the website?

**Comment by Samsinite** [comment]
Sure, I should be able to write up a first draft this weekend.

Thanks,
Sam

**Comment by Samsinite** [comment]
@locks I see that the documentation is in the comments, but what is the best way to view the rendered docs after making changes?

**Comment by Samsinite** [comment]
I also see that https://github.com/glimmerjs/glimmer-website/ is where the guides are at, so I can submit a PR there for the guides.

**Comment by rwjblue** [comment]
This repo has been merged with glimmerjs/glimmer.js (into a monorepo setup). I am not sure if this issue is still applicable, but if you could confirm it is still an ongoing concern and open it over there that would be very helpful.

Sorry for the noise, but thank you for your help!
