### ISSUE TITLE
`each` helper throwing "Must specify a key" error

### ISSUE THREAD

**Issue by asakusuma** [glimmerjs/glimmer-component#4]
A simple `each` loop doesn't seem to work.

```
{{#each list}}
  <li>{{this}}</li>
{{/each}}
```

Repro [commit](https://github.com/asakusuma/hello-glimmer/commit/2e1e8147b457d04656c6d5e995714d30f5139dd2) to `hello-glimmer`

```
Uncaught Error: Must specify a key for #each
    at Environment$$1.iterableFor (environment.js:175)
    at lists.js:23
    at AppendOpcodes.evaluate (opcodes.js:270)
    at VM.execute (append.js:288)
    at Object.render (template.js:116)
    at App.render (application.js:87)
    at App.boot (application.js:79)
    at index.js:4
```

**Comment by rwjblue** [comment]
The default `iteratorFor` implementation that glimmer-application uses, requires a `key` to be specified ([see here](https://github.com/glimmerjs/glimmer-application/blob/3c5f3124f7d899441799a7e301064a7392548465/src/environment.ts#L174-L176)).  Ember's version of `{{each` does this for you automatically by utilizing `Ember.guidFor`, but in a standalone glimmer environment you must manually specify the key to be used.

```hbs
{{#each list key="id" as |item|}}
  <li>{{item}}</li>
{{/each}}
```

**Comment by asakusuma** [comment]
Is `id` a reserved word for the index of an array? I'm confused as to what a key is in the context of an array. Array items might have a key, but the entire array? I also don't see this `key` concept in the handlebars docs.

**Comment by robbiepitts** [comment]
For an array you would use `{{#each list  key="@index" as |item|}}`.

**Comment by rwjblue** [comment]
They key generally is a property on each item in the array, or as @robbiepitts mentioned you can use the special value `"@index"`.

A similar concept exists in react land, and Ember just makes it slightly easier since it can use guidFor.

**Comment by robbiepitts** [comment]
Yes, sorry, meant to say, "array of non-objects (like strings)".

**Comment by asakusuma** [comment]
Thanks for the responses. This feels clunky to me, as it seems like we are allowing the complexity of specific scenario (array of objects) to complicate the API for a simple scenario (array of primitives). Is this `key` property documented anywhere? I don't see it on the handlebars [built-in helpers](http://handlebarsjs.com/builtin_helpers.html#iteration) page.

**Comment by tomdale** [comment]
@asakusuma It's not documented anywhere because documentation for Glimmer doesn't exist yet. :) It is not surprising that it's not on the Handlebars page since this is a concern that only applies to diffing re-renders.

**Comment by asakusuma** [comment]
To close the loop here, the suggested syntax works. I'm fine closing this, but we may want to leave open as a reminder for something to highlight in the eventual glimmer docs.

**Comment by acorncom** [comment]
@asakusuma Did I hit this well enough in https://www.glimmerjs.com/guides/templates-and-helpers ?  See the bottom of the page ...

**Comment by locks** [comment]
Closing for now, open an issue in the website repo for further discussion. Gracias :)

**Comment by asakusuma** [comment]
@acorncom yes, thanks!
