### ISSUE TITLE
Async functions cause reference error

### ISSUE THREAD

**Issue by remzr7** [glimmerjs/glimmer-component#41]
When I use async functions in my components I get reference error: can't find variable regeneratorRuntime

**Comment by sohara** [comment]
@remzr7 I think this feature relies on a babel polyfill. In ember-cli apps you can usually fix this by configuring babel options. In your `ember-cli-build.js` file you can add
```js
module.exports = function (defaults) {
  var app = new GlimmerApp(defaults, {
    'ember-cli-babel': {
      includePolyfill: true
    }
  });
}
```

**Comment by robbiepitts** [comment]
@sohara That doesn't work currently with `GlimmerApp` AFAIK.

**Comment by remzr7** [comment]
@sohara that's not working. I do see that the feature relies on polyfill but for glimmer that's not working

**Comment by mattmazzola** [comment]
Not sure if you already tried this but in the docs it says:

> Note: To get async/await to work you must create your project with the --web-component option, or add @glimmer/web-component to your package.json.

**Comment by robbiepitts** [comment]
Everyone hold your horses, let's see where this issue leads: https://github.com/glimmerjs/glimmer-website/issues/62

**Comment by locks** [comment]
Instructions now at https://github.com/glimmerjs/glimmer-application-pipeline#enabling-use-of-async-await-in-components.
