### ISSUE TITLE
Give more descriptive error message when using child component outside of parent's template

### ISSUE THREAD

**Issue by mattmazzola** [glimmerjs/glimmer-component#43]
Steps to reproduce:
1. create new default glimmer app
2. Add new component: `ember g glimmer-component parent-component`
3. Add new nested/child component: `ember g glimmer-component parent-component/child-component`

Put reference to child component in root/top level component instead of correctly in the parent-component.

This should generate error because as docs say:
> Our new component then is only useable from inside our [parent template] file

Actual:
```
environment.ts:193 Uncaught Error: Could not find template for child-component
    at Environment$$1.getComponentDefinition (environment.ts:193)
    at Environment$$1.hasComponentDefinition (environment.ts:159)
    at functions.js:226
    at Compilers.compile (functions.js:45)
    at compileStatement (scanner.js:17)
    at compileStatements (scanner.js:68)
    at CompilableTemplate.compileStatic (scanner.js:35)
    at CompilableTemplate.compileDynamic (scanner.js:50)
    at ComponentManager.layoutFor (component-manager.ts:111)
    at component.js:144
```

This is simple example with only few components but imagine when you have hundreds and someone accidentally places component in the wrong location perhaps by mistakenly copy/pasting or something and now the whole app won't render.

The error message says it can't find the template which is misleading and not helpful for actually fixing the problem.

Brand new to glimmer so I don't know if this is possible, but it would be really nice if it was able to say something like this:

Expected:
```
Component <child-component /> in glimmer-test/template.hbs at line 9 was attempted to be rendered outside of it's parent components template: "parent-component/template.hbs"
```

This tells you what the actual problem is, where the offending component is and where it can be used.

**Comment by rwjblue** [comment]
Great issue report, thank you!  These sorts of error details are absolutely worth getting right. I don't think we can exactly match what your expected output is, but we can get close.  We can definitely tell you what thing you attempted to render and from where, what I am unsure of is if we can actually figure out what you _meant_ to render (for the `"outside of it's parent components template: "parent-component/template.hbs"` part).

**Comment by rwjblue** [comment]
This repo has been merged with glimmerjs/glimmer.js (into a monorepo setup). I am not sure if this issue is still applicable, but if you could confirm it is still an ongoing concern and open it over there that would be very helpful.

Sorry for the noise, but thank you for your help!
