### ISSUE TITLE
Errors in actions are silently swallowed

### ISSUE THREAD

**Issue by topaxi** [glimmerjs/glimmer-component#44]
If an error is thrown in an action, nothing happens and nothing gets logged to the console.

**Comment by rwjblue** [comment]
This repo has been merged with glimmerjs/glimmer.js (into a monorepo setup). I am not sure if this issue is still applicable, but if you could confirm it is still an ongoing concern and open it over there that would be very helpful.

Sorry for the noise, but thank you for your help!
