### ISSUE TITLE
`@tracked` doesn't play nice

### ISSUE THREAD

**Issue by chadhietala** [glimmerjs/glimmer-component#45]
Based on https://github.com/glimmerjs/glimmer-application/issues/53, https://github.com/glimmerjs/glimmer-application/issues/50, and https://github.com/glimmerjs/glimmer-application/issues/43 there is a weird interaction with `@tracked` and scheduling a re-render. I thought I could fix it in https://github.com/glimmerjs/glimmer-application/pull/52, however @krisselden mentioned that we likely need to internalize the check for `CURRENT` in Glimmer VM it's self. You simply cannot have `@tracked` cause the re-render directly, and in stead you need to check to see if the transaction needs to start at all.

**Comment by habdelra** [comment]
I ran into this as well, I've seen a bunch of manifestations of this problems in various forms. Here's my attempt at the very simplest means to reproduce it (there's a console log that logs each rerender cycle).

https://github.com/habdelra/glimmerjs-infinite-rerender

<img width="605" alt="screen shot 2017-04-10 at 4 32 52 pm" src="https://cloud.githubusercontent.com/assets/61075/24881312/6c32ee4c-1e0b-11e7-87d1-9ba3af5267c2.png">

**Comment by krisselden** [comment]
@chadhietala #52 is fine for now, just not when multiple apps are on one page, unless they don't share anything.

**Comment by rwjblue** [comment]
This repo has been merged with glimmerjs/glimmer.js (into a monorepo setup). I am not sure if this issue is still applicable, but if you could confirm it is still an ongoing concern and open it over there that would be very helpful.

Sorry for the noise, but thank you for your help!
