### ISSUE TITLE
tracked property set in didInsertElement is not triggering a re-render

### ISSUE THREAD

**Issue by habdelra** [glimmerjs/glimmer-component#48]
I ran into a scenario where a modifying a tracked property was not triggering a rerender when set from within `didInsertElement`. Note that when I wrap the property setting within a `requestAnimationFrame` the re-render works. A sample github project demonstrating this issue is here: https://github.com/habdelra/glimmer-tracked-oddness

The component.ts looks like this:
```ts
import Component, { tracked } from "@glimmer/component";

export default class DemoComponent extends Component {
  @tracked
  foo: boolean = false;

  didInsertElement() {
    this.foo = true;
  }

}
```

the corresponding template looks like this:
```hbs
<div>
  <h1>Welcome to Glimmer!</h1>
  {{#if foo}}
    <div>I'm a foo!</div>
  {{/if}}
</div>
```

**Comment by robbiepitts** [comment]
Confirm. I've run into this too. Not sure if it's user error or a bug.

**Comment by tomdale** [comment]
This is approximately equivalent to a "backtracking re-render" and is not great for performance. Generally speaking, it means you are forcing Glimmer to re-render *during* the render process. If you can set the tracked property *before* rendering completes, that's ideal.

@habdelra @robbiepitts Can you share the use cases that led you to want to set a tracked property in `didInsertElement()`? There are some legit cases and we've bandied about proposals to let people do this in a constrained way. Either way, we should at least have a warning or error in development mode if you set a tracked property and we don't intend to re-render.

**Comment by habdelra** [comment]
I ran across it while debugging an unrelated problem and figured it was worthwhile to file the issue. to my knowledge, we're not doing actually doing this in the app we're building.

**Comment by robbiewain** [comment]
I ran into this same issue while trying to set a tracked property in a callback. Putting this code in the constructor had the same problem - no re-render.

```
export default class HackTheNews extends Component {
  @tracked stories: Story[];

  didInsertElement() {
    chrome.storage.local.get(({ stories }) => {
      this.stories = stories;
    });
  }
}
```

**Comment by rwjblue** [comment]
This repo has been merged with glimmerjs/glimmer.js (into a monorepo setup). I am not sure if this issue is still applicable, but if you could confirm it is still an ongoing concern and open it over there that would be very helpful.

Sorry for the noise, but thank you for your help!
