### ISSUE TITLE
Symbol object is not available in IE

### ISSUE THREAD

**Issue by MartinMalinda** [glimmerjs/glimmer-component#50]
Symbol object is used here
https://github.com/glimmerjs/glimmer-component/blob/master/src/tracked.ts#L65
Which is not at all supported in IE: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol#Browser_compatibility

Maybe at least IE11 should be supported? It still has >3% global usage.

**Comment by rwjblue** [comment]
I think the idea is that you would use a polyfill. Unfortunately, there is no easy way to configure this just yet.

**Comment by acorncom** [comment]
This issue currently affects the Ember website, where we're using Glimmer components for the header and footer. Any way we can help push this along?

**Comment by rwjblue** [comment]
This repo has been merged with glimmerjs/glimmer.js (into a monorepo setup). I am not sure if this issue is still applicable, but if you could confirm it is still an ongoing concern and open it over there that would be very helpful.

Sorry for the noise, but thank you for your help!
