### ISSUE TITLE
didUpdate hook called before component is rerendered

### ISSUE THREAD

**Issue by habdelra** [glimmerjs/glimmer-component#51]
The didUpdate hook is invoked before the component is re-rendered into the DOM. Here is a repo to reproduce the issue:  https://github.com/habdelra/glimmerjs-didUpdate-hook/

The component looks like this:
```ts
import Component, { tracked } from "@glimmer/component";

export default class GlimmerDidUpdateHook extends Component {
  updated = false;

  @tracked
  foo: boolean = false;

  didInsertElement() {
    setTimeout(() => {
      this.foo = true;
    }, 2000);
  }


  didUpdate() {
    if (!this.updated) {  // to compensate for infinite rerender bug
      this.updated = true;

      console.log('this.foo is ', this.foo);
      let fooElement = document.getElementById("foo");
      if (!fooElement) {
        console.log("Can't find foo");
      }
    }
  }

}

```

the template looks like this:
```hbs
<div>
  <h1>Welcome to Glimmer!</h1>
  {{#if foo}}
    <div id="foo">I'm a foo!</div>
  {{/if}}
</div>

```

This is what I see in the console:
<img width="639" alt="screen shot 2017-04-14 at 2 16 21 pm" src="https://cloud.githubusercontent.com/assets/61075/25051891/f981ba58-211c-11e7-865d-2d5feecbddfa.png">

**Comment by rwjblue** [comment]
This repo has been merged with glimmerjs/glimmer.js (into a monorepo setup). I am not sure if this issue is still applicable, but if you could confirm it is still an ongoing concern and open it over there that would be very helpful.

Sorry for the noise, but thank you for your help!
