### ISSUE TITLE
Cannot track a property on a referenced object

### ISSUE THREAD

**Issue by mixonic** [glimmerjs/glimmer-component#65]
A reproduction appropriate for http://glimmer-playground.netlify.com/.

```hbs
<div>
  <h1>Welcome to Glimmer!</h1>
  <br>
  Service#isMax: {{service.isMax}}

  <br>
  Component#isMax {{isMax}}
</div>
```

```js
import Component, { tracked } from '@glimmer/component';

class Service {
  @tracked
  isMax = false;

  constructor() {
    setTimeout(() => {
      this.isMax = true;
    }, 2000);
  }
}

export default class extends Component {
  @tracked
  service = new Service();

  @tracked('service')
  get isMax() {
    return this.service.isMax;
  }
}
```

Expected: After 2 seconds both flags swap to `true`
Actual: Only the `{{service.isMax}}` changes to `true`

Replaces: https://github.com/glimmerjs/glimmer-application/issues/87

**Comment by mixonic** [comment]
A terrible hack of a work around:

* https://gist.github.com/mixonic/acbc9b8d57819e2f2c77b206ab7f422e

**Comment by rwjblue** [comment]
This repo has been merged with glimmerjs/glimmer.js (into a monorepo setup). I am not sure if this issue is still applicable, but if you could confirm it is still an ongoing concern and open it over there that would be very helpful.

Sorry for the noise, but thank you for your help!
