### ISSUE TITLE
Glimme throws an error if template starts with `if`

### ISSUE THREAD

**Issue by andreisebastianc** [glimmerjs/glimmer-component#69]
After figuring it out it makes sense that 
```
<div>
  {{#if dataIsAvailable}}
    <svg></svg>
  {{else}}
    <p>No data available</p>
  {{/if}}
</div>
```
would work, while this
```
{{#if dataIsAvailable}}
  <svg></svg>
{{else}}
  <p>No data available</p>
{{/if}}
``` 
would not.

The error message is `Uncaught TypeError: expr.get is not a function` and you can figure it out eventually because the stack contains some references to OPCODES. However, as a newcomer, I failed to see any reference of this requirement in the docs.

**Comment by rwjblue** [comment]
Great point! We do indeed require a single root element at the moment. I completely agree that we should make sure the error message is more useful, and include some sort of reference in the docs.

**Comment by rwjblue** [comment]
This repo has been merged with glimmerjs/glimmer.js (into a monorepo setup). I am not sure if this issue is still applicable, but if you could confirm it is still an ongoing concern and open it over there that would be very helpful.

Sorry for the noise, but thank you for your help!
