### ISSUE TITLE
Not clear how to pass data to component in tests

### ISSUE THREAD

**Issue by andreisebastianc** [glimmerjs/glimmer-component#70]
I can't confirm if this works or not because of https://github.com/glimmerjs/glimmer-application/issues/95 .

I tried adding a test that does more then check the top-most div and didn't find any documentation on how this would look like, so I assumed something similar to how this is done in Ember would work:
```
  test('it renders an svg when data is available', async function(assert) {
    this.data = {
      "name": "display",
      "children": [
        {"name": "DirtySprite", "size": 8833},
        {"name": "LineSprite", "size": 1732},
        {"name": "RectSprite", "size": 3623},
        {"name": "TextSprite", "size": 10066}
      ]
    };
    await this.render(hbs`<bar-chart @data={{data}} />`);
    assert.ok(this.containerElement.querySelector('svg'));
  });
```

Can you confirm?

**Comment by robbiepitts** [comment]
Confirm. `this.set()` is what will solve this, but it doesn't exist yet. You would be able to do this:

```ts
test('it renders an svg when data is available', async function(assert) {
    this.set('data', {
      "name": "display",
      "children": [
        {"name": "DirtySprite", "size": 8833},
        {"name": "LineSprite", "size": 1732},
        {"name": "RectSprite", "size": 3623},
        {"name": "TextSprite", "size": 10066}
      ]
    });
    await this.render(hbs`<bar-chart @data={{data}} />`);
    assert.ok(this.containerElement.querySelector('svg'));
  });
```

**Comment by deepan83** [comment]
@robbiepitts We are building a suite of glimmer components and this would be key for it. Any timescales on this or possible workarounds for the moment? Happy to help if required.

**Comment by andreisebastianc-ccc** [comment]
Just use `this.property`. When `set` is made available, change them (or they may just work as is going forward).

**Comment by lcpriest** [comment]
@andreisebastianc-ccc any recommendations for doing the same for closure actions?

**Comment by acimpean-ccc** [comment]
@lcpriest at the moment I just ignore tests and wait until `set` is implemented

**Comment by lcpriest** [comment]
Thanks!
