### ISSUE TITLE
Fragment support

### ISSUE THREAD

**Issue by robbiepitts** [glimmerjs/glimmer-component#71]
It is possible to create a fragment component manager, register it, and use it with the `{{use-component-manager` pragma (which is behind a feature flag). Do we want to ship a fragment component manager in this package? Or do we want to support fragments in a different way? Or do we just want to say "do it yourself" (which I am fine with)?

I just feel like this is an ultra-hidden feature we might want to give more exposure to in one way or another since it is not insignificant. Here are a couple real-world use cases off the top of my head: 1) rendering into the shadow dom of a custom element; 2) higher-order components.

**Comment by rwjblue** [comment]
This repo has been merged with glimmerjs/glimmer.js (into a monorepo setup). I am not sure if this issue is still applicable, but if you could confirm it is still an ongoing concern and open it over there that would be very helpful.

Sorry for the noise, but thank you for your help!
